name: get-iplayer
version: 3.01
summary: A utility for downloading TV and radio from BBC iPlayer
description: BBC iPlayer Indexing Tool and PVR
confinement: devmode
grade: devel

apps:
  get-iplayer:
    command: scripts/run-cli.pl
  server:
    command: scripts/run-server.pl
    daemon: simple

parts:
  get-iplayer:
    source: https://github.com/get-iplayer/get_iplayer.git
    source-tag: v3.01
    plugin: dump
    stage-packages:
      - perl-base
      - libwww-perl
      - liblwp-protocol-https-perl
      - libmojolicious-perl
      - libxml-simple-perl
      - libxml-libxml-perl
      - libcgi-pm-perl
      - ffmpeg
      - atomicparsley
  launcher:
    plugin: dump
    source: .
    organize:
      run-cli.pl: scripts/run-cli.pl
run-server.pl: scripts/run-server.pl
