name: get-iplayer-ads20000
version: 3.01
summary: A utility for downloading TV and radio from BBC iPlayer
description: BBC iPlayer Indexing Tool and PVR
confinement: strict
grade: stable

apps:
  get-iplayer:
    command: run-cli.pl
    plugs:
      - network
  server:
    command: run-server.pl
    daemon: simple

parts:
  get-iplayer:
    source: https://github.com/get-iplayer/get_iplayer.git
    source-tag: v3.01
    plugin: dump
    stage-packages:
      - perl-base
      - libwww-perl
      - liblwp-protocol-https-perl
      - libmojolicious-perl
      - libxml-simple-perl
      - libxml-libxml-perl
      - libcgi-pm-perl
    after:
      - desktop-glib-only
      - ffmpeg
    install:
      mv README.md README-get-iplayer.md
  atomicparsley:
    plugin: dump
    source: https://bitbucket.org/wez/atomicparsley
    source-type: hg
    source-commit: 9183fff
    install:
      mv README.md README-atomicparsley.md
  launcher:
    plugin: dump
    source: .
    organize:
      run-cli.pl: scripts/run-cli.pl
      run-server.pl: scripts/run-server.pl
